### PR TITLE
Improve the view to separate important/less important info - #98

### PR DESCRIPTION
**Pull request by shilpaexaltcg**
Added View columns filter(mui-datatable) to select and view less important columns which will be hidden by default

### CODE REVIEW

**Comment by sylvestre** [comment]
This PR seems incorrect
please create a branch per changes, here, you have a bunch of changes at the same place

**Comment by sylvestre** [comment]
@shilpaexaltcg could you please fix the conflicts? thanks



```
Conflicting files
src/components/BugzillaComponents/index.jsx
src/components/Reportees/index.css
src/components/Reportees/index.jsx

```

**Comment by sylvestre** [comment]
If possible, I would prefer a single button with "View more information"
instead of the list of column.
Would it be possible to do that? Thanks

For the record, here is what I see currently:
image

**Comment by shilpaexaltcg** [comment]
@sylvestre You want a button for hiding and showing all the columns at once and not an option to select and and view single column right?

This is the default option provided by mui-datatable and can be changed. Although we can change this, in my opinion it gives more control to users. let me know your opinion on this.

**Comment by sylvestre** [comment]
Yeah, 
I would like this to be binary:
1. I want to only important thing
1. I want to see everything

We don't need column selections;
Thanks

**Comment by sylvestre** [comment]
and please push a clean PR. ;)

**Comment by shilpaexaltcg** [comment]
Created a new PR. Closing this

**Comment by sylvestre** [comment]
Moved here: https://github.com/mozilla/bugzilla-dashboard/pull/125

**Pull request closed without merging**
