### PR TITLE
Upgrade to Neutrino 9 RC + update dependencies

### PR DESCRIPTION
**Pull request by armenzg**
@helfi92 `yarn start` and `yarn test` do not show the warnings, however, `yarn build` does.

@helfi92 I don't see the warnings when running |yarn start| or |yarn test| but I see it when I run |yarn build|.

Should I report this for the Neutrino 9 release or not?

```
Armens-MacBook-Pro:bugzilla-dashboard armenzg$ yarn build
yarn run v1.15.2
$ webpack --mode production

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```

### CODE REVIEW

**Comment by helfi92** [comment]
Sound like a bug that needs to be fixed in Neutrino.

**Comment by armenzg** [comment]
Filed: https://github.com/neutrinojs/neutrino/issues/1367

**Comment by armenzg** [comment]
I saw that Eli landed a fix. How can I locally test that it got fixed?

I tried the following:

```bash
Armens-MacBook-Pro:neutrino armenzg$ cd neutrino/packages/neutrino
Armens-MacBook-Pro:neutrino armenzg$ yarn link
yarn link v1.15.2
success Registered "neutrino".
info You can now run `yarn link "neutrino"` in the projects where you want to use this package and it will be used instead.
✨  Done in 0.06s.
Armens-MacBook-Pro:neutrino armenzg$ cd ../../../bugzilla-dashboard/
Armens-MacBook-Pro:bugzilla-dashboard armenzg$ yarn link neutrino
yarn link v1.15.2
success Using linked package for "neutrino".
✨  Done in 0.06s.
Armens-MacBook-Pro:bugzilla-dashboard armenzg$ yarn build
yarn run v1.15.2
$ webpack --mode production
/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/cli.js:231
				throw err;
				^

Error: Cannot find module 'yargs-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/armenzg/repos/bugzilla-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/armenzg/repos/neutrino/packages/neutrino/index.js:1:83)
    at Module._compile (/Users/armenzg/repos/bugzilla-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/armenzg/repos/bugzilla-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/armenzg/repos/bugzilla-dashboard/webpack.config.js:4:18)
    at Module._compile (/Users/armenzg/repos/bugzilla-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/armenzg/repos/bugzilla-dashboard/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/convert-argv.js:115:13)
    at requireConfig (/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/convert-argv.js:117:6)
    at /Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/convert-argv.js:122:15)
    at yargs.parse (/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/cli.js:228:39)
    at Object.parse (/Users/armenzg/repos/bugzilla-dashboard/node_modules/yargs/yargs.js:567:18)
    at /Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/cli.js:206:8
    at Object.<anonymous> (/Users/armenzg/repos/bugzilla-dashboard/node_modules/webpack-cli/bin/cli.js:505:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by helfi92** [comment]
> I saw that Eli landed a fix. How can I locally test that it got fixed?

You could try to see if the change was released. I think releases are done manually.

**Comment by helfi92** [comment]
The Neutrino repo is a set of packages. You would have to link the affected packages.

**Pull request merged**
