### PR TITLE
WIP - Replace tables with a more advanced component 

### PR DESCRIPTION
**Pull request by shilpaexaltcg**
This PR is for issue #109.  Implemented mui-datatable component for Reportees view.

### CODE REVIEW

**Comment by shilpaexaltcg** [comment]
@sylvestre I've replaced the reportees table with mui-datatable component. Some checks are failing and I'm unable to view the details of failed checks. Please help me with this

**Comment by sylvestre** [comment]
I don't have permissions either @armenzg probably have the permissions
maybe you don't use the last version of some libs?

**Comment by armenzg** [comment]
Are you referring to the Snyk errors? Let me check

**Comment by armenzg** [comment]
This one is a bit tricky. Adding `mui-datatables` user `lodash.merge` which has a vulnerability affecting all versions of it:
https://app.snyk.io/vuln/SNYK-JS-LODASHMERGE-173732

Checking the [Hackerone report](https://hackerone.com/reports/380873) I can see that a fix was introduced in [4.7.11](https://www.npmjs.com/package/lodash), however, `lodash.merge` is still releasing version [4.6.1](https://www.npmjs.com/package/lodash.merge) from a year ago.

@helfi92 how do you feel about using `mui-datatables` knowing the above?

I'm going to file a hackerone report.

**Comment by sylvestre** [comment]
@armenzg doesn't seem super critical. What do you think about accepting this PR and opening a new issue to keep track of the security issue? Thanks

**Comment by armenzg** [comment]
That's fine with me as long as we file an issue to track it.

Filed upstream for now: https://github.com/gregnb/mui-datatables/issues/694

**Pull request merged**
